name: Publication Docker image Php
on:
  push:
    branches: [main]
jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        phpversion: [-7.4, -8.0.3, -8.1, -8.2, -8.3.1,-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all
      - name: Setup Docker Buildx php${{ matrix.phpversion }}
        uses: docker/setup-buildx-action@v1
        id: buildx
      - name: Cache Docker Image Layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Build and Push Docker Image php${{ matrix.phpversion }}
        uses: docker/build-push-action@v2
        id: docker_build
        with:
          context: ./
          file: ./php${{ matrix.phpversion }}/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          platforms: linux/386, linux/amd64, linux/arm64
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/php:php${{ matrix.phpversion }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
      - name: Verify
        run: echo ${{ steps.docker_build.outputs.digest }}
